name: CatCraftTitle
version: ${project.version}
main: catcraft.title.CatCraftTitlePlugin
api-version: 1.16
folia-supported: true
authors: [CatCraft]
description: 多功能称号&后缀系统，支持GUI、多数据库、RGB渐变
softdepend: [PlaceholderAPI]
permissions:
  catcraft.admin:
    description: 管理员权限
    default: op
  catcraft.player:
    description: 玩家基础权限
    default: true
commands:
  catcraft:
    description: CatCraft玩家头衔管理
    usage: /catcraft help
  titleadmin:
    description: CatCraft管理员头衔管理
    permission: catcraft.admin
    usage: /titleadmin help